spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/shopping
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: MYSQL
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: default, sample